name: pr

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: echo "RUST_TOOLCHAIN=$(cat ./rust-toolchain)" >> $GITHUB_ENV
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: debug-build
      - name: Make test
        run: make test
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "RUST_TOOLCHAIN=$(cat ./rust-toolchain)" >> $GITHUB_ENV
          echo "RUST_TOOLCHAIN_NIGHTLY=$(cat ./rust-toolchain-nightly)" >> $GITHUB_ENV
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN_NIGHTLY }}
          components: rustfmt
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: debug-build-nightly
      - name: Make lint
        run: make lint
  semver:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - uses: actions/checkout@v4
      # Manually extract labels because rymndhng/release-on-push-action can't do this correctly on a PR
      - name: Extract labels
        id: extract_version_bump
        shell: bash
        run: |
          if [ ${{contains( github.event.pull_request.labels.*.name, 'release:major')}} = true ]; then
            echo "bump_version=major" >> $GITHUB_OUTPUT
          elif [ ${{contains( github.event.pull_request.labels.*.name, 'release:minor')}} = true ]; then
            echo "bump_version=minor" >> $GITHUB_OUTPUT
          elif [ ${{contains( github.event.pull_request.labels.*.name, 'norelease')}} = true ]; then
            echo "bump_version=" >> $GITHUB_OUTPUT
          else
            echo "bump_version=patch" >> $GITHUB_OUTPUT
          fi
      - name: Calculate next version
        id: calc_version
        if: ${{ steps.extract_version_bump.outputs.bump_version }} != ""
        uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: ${{ steps.extract_version_bump.outputs.bump_version }}
          tag_prefix: ""
          dry_run: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Print version
        run: | 
          echo "${{steps.calc_version.outputs.version}} ${{github.event.pull_request.labels}}"
          echo "${{ steps.extract_version_bump.outputs.bump_version }}"
          echo "${{toJson(github.event.pull_request.labels.*.name)}}"
      - name: Set version
        if: ${{ steps.extract_version_bump.outputs.bump_version }} != ""
        run: |
          sed -i "s/^version = \".*\"$/version = \"${{ steps.calc_version.outputs.version }}\"/" Cargo.toml
      - name: Commit new version to main but don't push
        if: ${{ steps.extract_version_bump.outputs.bump_version }} != ""
        run: |
          git config --global user.email "rust-maintainers@moiaorg.onmicrosoft.com"
          git config --global user.name "MOIA Rust Maintainers"
          git commit -am "Phantom release ${{ steps.calc_version.outputs.version }} [skip ci]"
      - name: Check semver
        if: ${{ steps.extract_version_bump.outputs.bump_version }} != ""
        uses: obi1kenobi/cargo-semver-checks-action@v2
        with:
          version-tag-prefix: ''
